### PR TITLE
Refactor lane edge reference and clarify lane numbering

### PR DESCRIPTION
**Pull request by j-d-b**
This PR resolves issues #66 and #67 by:

1. Removing `lane_edge_reference` from the **lane** entity
2. Adding equivalent `lane_number_start_side` field to the **road event** entity
3. Clarifying that  `lane_number` must start at "1" for the lane closest to the roadside edge indicated by `lane_number_start_side`
4. Clarifying that an increase of `lane_number` by "1" represents moving one lane over away from the direction indicated by `lane_number_start_side`

### CODE REVIEW

**Comment by sknick-iastate** [comment]
This looks good to me. A couple of comments based on our last spec group meeting and discussing counting shoulders, bike lanes, etc  in the lane number

- I'm not sure I would interpret that shoulder/non-vehicle lanes should be included in the lane number without the background discussion we have been having recently. Especially since I don't think most agencies include these in the lane numbering currently. It may also be due to us including shoulders in the lanes table.  Should we add some text in the `lane_number` description that says this? It may also be good to say `lane_id` instead of just lane when referring to the numbering as well. 

- Should we add a shoulder with a lane number to the examples (specifically a right shoulder to `road_event_id` 12345 in both the multi-point and linestring example)

**Comment by rchoyler** [comment]
Recommend NOT including shoulders in the lane numbering sequence; unless they are designed to accommodate standard vehicular travel which is equivalent to that of the main lanes (i.e. similar road surface, supports same speed limit, same legality, etc.); such as lanes designated for use only during rush hour periods, HOV/HOT lanes, etc. Perhaps "unimproved shoulders" could be designated as LS (left shoulder) & RS (right shoulder). If numeric values are required, then perhaps use 0 for the left shoulder and 99 for the right shoulder.

**Comment by j-d-b** [comment]
Note #94 completely replaces this. If #94 is not approved/merged, this PR will again be relevant. If #94 if merged, this PR can be closed.

**Comment by j-d-b** [comment]
Closed with #94 merge

**Pull request closed without merging**
