### PR TITLE
Update full-spec.md

### PR DESCRIPTION
**Pull request by heidiguenin**
minor grammar & consistency updates I caught while scanning the spec

### CODE REVIEW

**Comment by Mahsa-Ettefagh** [comment]
**This pull request is now open for voting. Please cast your vote by leaving a “yes”, “no”, or “neutral” comment under the pull request. The voting will remain open until Wednesday, October 16th.**

**Comment by barbeau** [comment]
yes

**Comment by sergebeaudry** [comment]
Yes

**Comment by davidcraig4300** [comment]
Yes

**Comment by CraigMoore-Sea** [comment]
Yes

**Comment by SinclairStolle-IowaDOT** [comment]
yes

**Comment by GreyIC** [comment]
Yes

**Comment by sknick-iastate** [comment]
yes

**Comment by DavidRush123** [comment]
Yes

**Comment by Mahsa-Ettefagh** [comment]
On behalf of Derald Dudley - U.S,DOT - Yes

**Comment by j-d-b** [comment]
My vote: yes.

However, it seems odd that this type of PR is subject to the same process as PRs which propose changes to the specification since it doesn't include any spec changes.

I think it would be beneficial to have maintainers who are able to approve/merge this type of PR (no changes to the spec) without voting.

There are more inconsistencies like this throughout the spec and examples; having to wait for staged released and voting will slow these fixes.

**Comment by kpwebb** [comment]
Yes

**Comment by natedeshmukhtowery** [comment]
@j-d-b agree 100%. For this first time around, USDOT wanted the community to weigh in on ALL changes to the specification, no matter how small. But agree that trusted administrators for WZDx should be able to make these types of changes in the future.

**Pull request merged**
