### PR TITLE
specify EPSG:4326 datum for coordinates

### PR DESCRIPTION
**Pull request by sbma44**
refs #15

### CODE REVIEW

**Comment by Mahsa-Ettefagh** [comment]
**This pull request is not open for voting. Please cast your vote by leaving a “yes”, “no”, or “neutral” comment under the pull request. The voting will remain open until Wednesday, October 16th.**

**Comment by barbeau** [comment]
yes

**Comment by sergebeaudry** [comment]
Yes

**Comment by davidcraig4300** [comment]
Yes

**Comment by sghorbanian** [comment]
yes

**Comment by CraigMoore-Sea** [comment]
Yes

**Comment by SinclairStolle-IowaDOT** [comment]
Yes

**Comment by GreyIC** [comment]
Yes

**Comment by DavidRush123** [comment]
Yes

**Comment by sknick-iastate** [comment]
yes

**Comment by Mahsa-Ettefagh** [comment]
On behalf of Derald Dudley - USDOT - Yes

**Comment by Joseph-Kuenzi** [comment]
Yes

**Comment by j-d-b** [comment]
Yes

**Comment by kpwebb** [comment]
Yes

**Comment by DrewClark-KY** [comment]
Yes - Kentucky Transportation Cabinet

**Comment by Mahsa-Ettefagh** [comment]
Closing this pull request since the recommended changes will be incorporated into version 2 as part of [PR#53](https://github.com/usdot-jpo-ode/jpo-wzdx/pull/53)

**Pull request closed without merging**
