### PR TITLE
Relational Mobility Impact and Lane Level Impacts/Restrictions

### PR DESCRIPTION
**Pull request by sknick-iastate**
This pull request adapts PR #44 to the relational data model that should be approved in PR #54.  See PR #44 for additional details of why the changes are being made.

**What has changed?**

- Added a lanes table which allows for the status of individual lanes to be identified
- Added a lane restrictions table which allows for restrictions to be identified for individual lanes.
- The structure change has resulted in some enumerations in `lane_type` being converted into `lane_status`. Specifically the `shift-left`, `shift-right`, etc that are not a type of lane but the impact on the lane
- Added a vehicle impact field to the road events table which provides a high level impact of the closure

**A couple of notes:**

- The current changes do not require individual lanes and lane groups can still be used within the lanes table (`lane_type` = `left-2-lanes`). 
- Producers can continue to report based on `lane_type` as defined in version 1.1 but also provide the ability to report by `lane_number` with the supporting `lane_edge_reference` to identify how the lanes are being numbered.  If the lanes table is produced I have required `lane_type` and made the lane numbering field optional since this is the way most producers that I am aware of provide and collect the data currently.  I am happy to modify this based on feedback.

**Things not addressed:**
There has been some discussion in other [pull requests]( https://github.com/usdot-jpo-ode/jpo-wzdx/pull/50#issuecomment-554679851) on a travel path effect field that would be located in this table.  I didn't include that but it could be added or handled in a separate PR.

### CODE REVIEW

**Comment by DeraldDudley** [comment]
Yes - USDOT

**Comment by CraigMoore-Sea** [comment]
Yes - Seattle DOT

**Comment by davidcraig4300** [comment]
Yes - GM

**Comment by sknick-iastate** [comment]
Yes - Iowa State University

**Comment by natedeshmukhtowery** [comment]
Yes, on behalf of City of Detroit's Sam Krassenstein

**Comment by sergebeaudry** [comment]
Yes- ver-mac

**Comment by sghorbanian** [comment]
yes - Uber ATG

**Comment by mikedavidson-paturnpike** [comment]
Yes - PA Turnpike

**Comment by natedeshmukhtowery** [comment]
Yes - on behalf of Faisal Saleem, Maricopa County DOT

**Comment by charlottetao** [comment]
Yes - Lyft Level 5

**Comment by DrewClark-KY** [comment]
Yes - Kentucky Transportation Cabinet

**Comment by cfelice** [comment]
Yes - Utah Dept. of Transportation (UDOT)

**Comment by GreyIC** [comment]
Yes on behalf of INRIX.

**Pull request merged**
