### PR TITLE
Refactor LaneType enumeration to deprecate values that can be determined from other properties, such as order, status, and restrictions

### LINKED ISSUE #137: Refactor LaneType enumeration: remove or deprecate values that reference a side or position on the roadway
This issue proposes examining and then refactoring the lane type enumeration to remove or deprecate values that reference a position on the road (`left`, `right`, `middle`,  or `center`), when the location can be determined by the lane's `order` property. 

## Background
There was a large refactoring of the [lane type enumeration](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/enumerated-types/derived-from-its-standards/lane_type.md) and [lane entity](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/data-tables/lanes.md) for the v3.0 release (see #94). The removal of lane types that reference a location on the road was discussed during the v3.0 cycle, but was deferred at the time. However, a few updates were made as a gateway to this change:

- A required `order` property was added to the lane entity to indicate a lane's position in the sequence of lanes on the roadway
- Generic `lane` and `shoulder` lane types were added 

Thus (in v3.0) the location of a lane on the roadway is known from the `order` property—this property alone indicates if the lane is on the left, right, center, etc. The lane's `type` value (one of the lane type enumerated type values) does not need to include the location information. `lane` and `shoulder` were added already and can be used instead of `left-lane`, `right-lane`, `middle-lane`, `center-lane` and `left-shoulder`, `right-shoulder` respectively.

## List of current (v3.0) lane types that reference a location

`left-lane`: The leftmost lane
`right-lane`: The rightmost lane
`middle-lane`: A lane that is not the rightmost or leftmost lane
`center-lane`: The center-most lane when the total number of lanes is odd
`right-turning-lane`: A right lane where right turns are permissible
`left-turning-lane`: A left lane where left turns are permissible
`right-exit-lane`: The right lane where the lane provides an egress with a ramp
`left-exit-lane`: The left lane where the lane provides an egress with a ramp
`right-merging-lane`: The right lane where the lane ends with a gradual merge with the second most lane
`left-merging-lane`: The left lane where the lanes ends by a gradual merge with the second most left lane
`right-exit-ramp`: The (first) exit ramp with an egress on the right in the direction of flow at an interchange
`right-second-exit-ramp`: The second exit ramp with an egress on the right in the direction of flow at an interchange
`right-entrance-ramp`: The (first) entrance ramp with an ingress on the right in the direction of flow at an interchange
`right-second-entrance-ramp`: The second entrance ramp with an ingress on the right in the direction of flow at an interchange
`left-exit-ramp`: The (first) exit ramp with an egress on the left in the direction of flow at an interchange
`left-second-exit-ramp`: The second exit ramp with an egress on the left in the direction of flow at an interchange
`left-entrance-ramp`: The (first) entrance ramp with an ingress on the left in the direction of flow at an interchange
`left-second-entrance-ramp`: The second entrance ramp with an ingress on the left in the direction of flow at an interchange
`right-shoulder`: The outer shoulder or the rightmost shoulder
`left-shoulder`: The inner shoulder or the leftmost shoulder

## List of lane types that can be removed without losing information
`left-lane`: use `lane` instead
`right-lane`: use `lane` instead
`middle-lane`: use `lane` instead
`center-lane`: use `lane` instead

`right-shoulder`: use `shoulder` instead
`left-shoulder`: use `shoulder` instead

## List of lane types that should remain (removing would lose functionality)
`right-turning-lane`: Indicates not only that it is a right lane, but that right lanes are allowed (not covered by `order`). Suggest updating the description to remove the qualification that it must also be a right lane
`left-turning-lane`: Indicates not only that it is a left lane, but that left turn are allowed (not covered by `order`). Suggest updating the description to remove the qualification that it must also be a left lane

Based on the descriptions above this should be able to be removed and replaced with a new `exit-lane` value, as the `right` and `left` don't indicate the direction of the exit lane, just it's position.

`right-merging-lane`: The right lane where the lane ends with a gradual merge with the second most lane
`left-merging-lane`: The left lane where the lanes ends by a gradual merge with the second most left lane

These are confusing as by description the `left` and `right` refer to the location not the direction of the merge. If the descriptions are accurate these can be replaced with a new `merging-lane` type. Alternatively they could stay and the description could change to indicate that the `left` and `right` refer to the direction of the merge, not the position of the lane (though that may be unnecessary as the merge direction may be obvious from the position).

`right-exit-ramp`: The (first) exit ramp with an egress on the right in the direction of flow at an interchange
`right-second-exit-ramp`: The second exit ramp with an egress on the right in the direction of flow at an interchange
`right-entrance-ramp`: The (first) entrance ramp with an ingress on the right in the direction of flow at an interchange
`right-second-entrance-ramp`: The second entrance ramp with an ingress on the right in the direction of flow at an interchange
`left-exit-ramp`: The (first) exit ramp with an egress on the left in the direction of flow at an interchange
`left-second-exit-ramp`: The second exit ramp with an egress on the left in the direction of flow at an interchange
`left-entrance-ramp`: The (first) entrance ramp with an ingress on the left in the direction of flow at an interchange
`left-second-entrance-ramp`: The second entrance ramp with an ingress on the left in the direction of flow at an interchange 

I'm not sure what the first/second terminology refers to so these need more discussion.

### PR DESCRIPTION
**Pull request by j-d-b**
This PR resolves #137.

The changes were made following the most recent proposal in that issue, that is

1. ~~Deprecate `left-lane`, `right-lane`, `middle-lane`, `center-lane` and use `lane` (which is already in the spec) instead~~
2. ~~Deprecate `left-shoulder`, `right-shoulder` and use `shoulder` (which is already in the spec) instead~~
3. ~~Change description for `right-turning-lane`, `left-turning-lane` to clarify the lane's position can be anywhere (specified by `order`) and that the "left" and "right" only refer to the direction of the turn~~
4. ~~Change description for `right-exit-lane`, `left-exit-lane` to clarify the lane's position can be anywhere (specified by `order`) that the "left" and "right" only refer to the direction of the exit. Additionally, note this lane can be a "ramp".~~
5. ~~Deprecate `right-exit-ramp`, `right-second-exit-ramp`, `left-exit-ramp`, `left-second-exit-ramp`; these are encompassed by the changes in 4.~~
6. ~~Add new `right-entrance-lane` and `left-entrance-lane` types. Clarify in the  to clarify the lane's position can be anywhere (specified by `order`) that the "left" and "right" only refer to the direction of ingress. Additionally, note this lane can be a "ramp"~~
7. ~~Deprecate `right-entrance-ramp`, `right-second-entrance-ramp`, `left-entrance-ramp`, `left-second-entrance-ramp`; these are encompassed by the changes in 6.~~
8. ~~Deprecate `right-merging-lane`, `left-merging-lane`; these can be specified by with the [LaneStatus](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/enumerated-types/LaneStatus.md) of a lane (`merge-left` or `merge-right`)~~

Edit: see [below](https://github.com/usdot-jpo-ode/jpo-wzdx/pull/147#issuecomment-761233670) for the updated proposal based on discussion since the first draft PR was made.

### CODE REVIEW

**Review by sknick-iastate — APPROVED** [review]

**Review by chuehlien — APPROVED** [review]
Made some minor changes based on the PR description - please review my changes prior to merging.

**Review by j-d-b — COMMENTED** [review]
@chuehlien The deprecated values should not be removed as they are still allowable values. There isn't a way to indicate a value of an enum is deprecated in JSON Schema. There isn't a way for properties either (in JSON Schema draft 7 which we're using; there is in the newest version) but at least then I can write in the description.

**Comment by chuehlien** [comment]
> @chuehlien The deprecated values should not be removed as they are still allowable values. There isn't a way to indicate a value of an enum is deprecated in JSON Schema. There isn't a way for properties either (in JSON Schema draft 7 which we're using; there is in the newest version) but at least then I can write in the description.

Got it - thanks for clarifying this! I added the ramps/merging lanes that I had removed back in.

**Comment by j-d-b** [comment]
Thinking about this more, as part of this cleanup it may be worthwhile to remove the "lane" suffix from many of the lane types. This suffix is implied in all cases and is already not used on `shoulder` and `sidewalk`. See below for the changes:

This was inspired by #149 as this change would remove having to define the difference between a "ramp" and "lane" or choose one of the terms for the lane type.

1. `lane` -> `generic`
2. `right-exit-lane` and `left-exit-lane` -> `right-exit` and `left-exit`
3. `right-turning-lane` and `left-turning-lane` -> `right-turning` and `left-turning` (or `turn`, open to comments here but want consistency with `center-left-turn`, so that should change to `turning` or these should be `turn`)
4. `hov-lane` -> `hov`
5. `right-entrance-lane` and `left-entrance-lane` -> `right-entrance` and `left-entrance`
6. `center-left-turn-lane` -> `center-left-turning` (see comment in 3.)
7. `alternating-flow-lane` -> `alternating-flow`
8. `reversible-lane` -> `reversible`

The list of non-deprecated lane types would then be:

```
generic
shoulder
sidewalk
right-exit
left-exit
right-turning (or "right-turn")
left-turning (or "left-turn")
hov
bike (this is the only one that sounds weird—thoughts on changing this to "bicycle" for clarity?)
right-entrance
left-entrance
center-left-turning (or "center-left-turn")
alternating-flow
reversible
```

All types in v3.0 except `shoulder` and `sidewalk` would be deprecated as the rest are new.

We would also remove the connection to the TMDD (which is already on its way out) which would clean up the table and allow for consistency with the rest of the specification enumerated types.

All, let me know thoughts on this. If we are going to make this kind of change, doing it sooner when we only have a few producers and are already deprecating many of the types is advisable.

**Comment by j-d-b** [comment]
@sknick-iastate @DeraldDudley @CraigMoore-Sea check out the above proposal and let me know your thoughts. I'll wait for some feedback before making any changes to the PR

**Comment by daylesworth** [comment]
@j-d-b, is there a goal to align these with SAE J2735 lane types (I guess this question could apply across all of WZDx, and other ITS standards)? If so, does DOT have permission from SAE to share relevant parts of their standards in this forum? Do we need permission to simply align the lexicon without sharing implementation details of the standards? If someone can answer these questions then I'm happy to provide feedback regarding alignment with J2735 (including lane types and attributes), but I only have access to published SAE standards and not WIP.

**Comment by j-d-b** [comment]
@daylesworth yes the goal is to align with existing standards where it is logical and matches the intended use of the standard. I don't have access to the SAE J2735 document. If its possible for you to post the lane types here, that would be helpful.

**Comment by daylesworth** [comment]
@j-d-b, I have a personally-licensed copy of the standard but it has a copyright notice that restricts any reproduction without permission from SAE, so I think DOT should request permission for this effort. Instructions can be found here... [https://www.sae.org/about/legal-policies?tab=4]

That said, here are the key differences...
- treats HOV as an attribute/restriction of a "vehicle" lane type (other attributes include bus, taxi, etc.)
- treats allowed maneuvers (left, right, u-turn, etc.) independently from lane types and attributes
- has several lane types not proposed here, including crosswalk, median, striping, tracked vehicle (trains/trolleys), and parking

**Comment by j-d-b** [comment]
@daylesworth thanks for enumerating the key differences. My comments below:

>     * treats HOV as an attribute/restriction of a "vehicle" lane type (other attributes include bus, taxi, etc.)

I like that approach. In fact, in WZDx there are already HOV-related restrictions in the [RoadRestriction](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/enumerated-types/RoadRestriction.md) enumerated type. Is there any value in the `hov-lane` lane type? 

More generally, what are producers using these lane types for? I can answer for MassDOT, where the lane type string is used to render a lane graphic for human use. 

>     * treats allowed maneuvers (left, right, u-turn, etc.) independently from lane types and attributes

Separating the allowed maneuver from the lane type is similar logic as treating the "hov" designation as a restriction rather than a lane "type". I support this as well. I'm hoping to make the lane type enumeration as minimal as possible. Many of the current lanes types could be removed and the functionality moved to either a restriction or the status. E.g. `exit-lane`, could be indicated by a lane type of `lane` with a restriction of `exit-only`.

>     * has several lane types not proposed here, including crosswalk, median, striping, tracked vehicle (trains/trolleys), and parking

This one might tie into being able to offer lane-level geometry, which is not something. Thus it is assumed that all lanes are parallel, which may mean crosswalk, striping. I don't feel like tracked vehicle fits in as well. `parking` I think should be added.

**Comment by natedeshmukhtowery** [comment]
Re. access to J2735, USDOT is looking into access to the relevant sections for this PR - thanks for raising, and stay tuned!

**Comment by j-d-b** [comment]
I feel that more discussion needs to happen regarding lane types—see #149 as well. Once we decide how we want to handle lane types in WZDx, then we can make a clear change and go with that going forward.

**Comment by j-d-b** [comment]
The co-chairs have reviewed SAE J2735 and though we are not going to implement lane types as done in that standard, it is useful to see allowed maneuvers and restrictions like "hov" being treated separately from the lane's type.

We next discussed what the value of the lane type is in WZDx—what is the utility of this field? Is it used to distinguish which modes of transportation are allowed (e.g. bike-lane, sidewalk, vehicle-lane)? Does it indicate if vehicles (e.g. cars, trucks) are allowed on it?

What was clear is that there needs to be more discussion before we can propose a final solution for describing lanes. Thus this PR will address *only* the simple change of removing the "sides" of the roadway from the list of lane types and leave the ambiguous and incomplete list, to be addressed in a future release.

Thus the changes are as follows:

1. Deprecate `left-lane`, `right-lane`, `middle-lane`, `center-lane` and use `lane` (which is already in the spec) instead
2. Deprecate `left-shoulder`, `right-shoulder` and use `shoulder` (which is already in the spec) instead
3. Change description for `right-turning-lane`, `left-turning-lane` to clarify the lane's position can be anywhere (specified by order) and that the "left" and "right" only refer to the direction of the turn
4. Change description for `right-exit-lane`, `left-exit-lane`, `right-exit-ramp`, `left-exit-ramp` to clarify the lane's position can be anywhere (specified by order) that the "left" and "right" only refer to the direction of the exit.
5. Deprecate `right-second-exit-ramp`, `left-second-exit-ramp`; these are encompassed by the changes in 4.
6. Change description for `right-entrance-ramp`, `left-entrance-ramp` to clarify the lane's position can be anywhere (specified by order) that the "left" and "right" only refer to the direction of the entrance.
7. Deprecate `right-second-entrance-ramp`, `left-second-entrance-ramp`; these are encompassed by the changes in 6.
8. Deprecate right-merging-lane, left-merging-lane; these can be specified by with the [LaneStatus](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/spec-content/enumerated-types/LaneStatus.md) of a lane (merge-left or merge-right)

**Comment by j-d-b** [comment]
In summary, this PR currently results in the following non-deprecated lane types:

```
lane
right-turning-lane
left-turning-lane
right-exit-lane
left-exit-lane
right-exit-ramp
left-exit-ramp
right-entrance-ramp
left-entrance-ramp
sidewalk
bike-lane
shoulder
center-left-turn-lane
```

Here is an incomplete proposal for even simpler lane types, for discussion:

```
General/Normal/Travel/Main/Vehicle (need to choose one term)
Sidewalk
Bike lane
Exit ramp/lane
Entrance ramp/lane
Shoulder
Parking (new functionality)
Median (new functionality)
Center left turn lane
```

The second list drops the ability to tell the direction of egress/ingress of an exit/entrance ramp/lane from the lane type (maybe this doesn't matter). It also drops the turning lanes, which are incomplete and not too helpful anyway as there is a lot of functionality missing ("left turn only",  "straight only", "right or left turns" etc.). As done in SAE J2735, perhaps the turns (what maneuvers are allowed) should not be part of the lane type. Then the question is whether we want to address that in WZDx at all...

**Pull request merged**
