### PR TITLE
Add workType field to activity definition common core data

### PR DESCRIPTION
**Pull request by j-d-b**
## Issue
I'm part of a team working with MassDOT to implement the WZDx spec. MassDOT currently uses and would like to disseminate `Work Type`, though it is not included in the current version of the WZDx spec. We feel this field would be beneficial for other entities/DOTs as well.

Support for this field has also been expressed in Issue #22.

## Proposal
I've updated the common core data to include an optional (for backwards compatibility) `workType` in both `common-core-dictionary.md` and `full-spec.md`. For flexibility, this field is proposed to be a string, though MassDOT uses a finite set of work type values, so there is potential for this to be changed to an enumerated type in the future.

## Examples and Current Use
I updated the MassDOT examples to show this field in use. The other examples are still valid as the `workType` field is optional.

For reference, MassDOT is currently using the following options for `workType`:
* `Repaving`
* `Bridge Repair`
* `Bridge Deck Replacement`
* `Guardrail Repair`
* `Maintenance`
* `Other`

### CODE REVIEW

**Comment by sknick-iastate** [comment]
I recommend that we dig into the WZAD Data Dictionary more to make sure this aligns with it. Just briefly looking into it, it looks like WorkType is actually a data frame and that the field name we should probably be using is workClassificationType.  Again this was me just briefly searching through the data dictionary and would need to be verified and updated.

I also think it would be beneficial to have enumerations.  I think we can likely put a good initial list together (possibly from an existing standard) and modify it over time.

**Comment by sergebeaudry** [comment]
I agree with the proposed idea. proposed field  Workclassificationtype as defined in section 3.2 of the data dictionnary [https://collaboration.fhwa.dot.gov/wzmp/Data%20DictionaryDocuments/WZAD%20Data%20Dictionary_VERSION%202.pdf](url)  looks adequate.   defining an enumaration from MASSdot and adding others might be a good start

**Comment by j-d-b** [comment]
@sergebeaudry @sknick-iastate Good idea; thanks for finding this section in the data dictionary. I'll update this PR to use the `WorkType` data frame with `workClassificationType` and `workClassificationDetail` enumerated types. 

The `workClassificationType` enumeration is defined in the data dictionary, however the `workClassificationDetail` is undefined. MassDOT's `workType` options I mentioned in the PR mostly fall under the `Construction` classification. Ideally we'd collaborate to define enumerated types for `workClassificationDetail`. I can use MassDOT's enumerations

* `Repaving`
* `Bridge Repair`
* `Bridge Deck Replacement`
* `Guardrail Repair`
* `Other`

For the `Construction` `workClassificationType`, though we don't have anything defined yet for the other classifications. I can put samples together for the PR though.

**Comment by CraigMoore-Sea** [comment]
What the use case on the consumer side for this data?

**Comment by davidcraig4300** [comment]
Maybe I am missing something, but Section 3.2 of the WZDA is not helpful in this case.
workClassification
Detail
TBD -- developed by each region Detailed work type grouped

Our use case is the following:  We need HD maps for our automated driving vehicles.  The HD maps we use are LiDAR scans of the roads to create 10cm absolute coordinate accurate maps.  Maintenance of these LiDAR scanned maps is very challenging!  Mainly because gathering “good” data to determine which roads have changed and to what degree they have changed is exceptionally hard.  We see this standard as a possible 1st step in reporting changes to the roads, but without know what has changed, it is not very usable to map makers.   
I would recommend the following categorization of construction zones:
0	 No change, this would be used for trash cleaning, mowing, and other general landscaping maintenance. 
1	Sign replacement and repair, non-traffic control
2	Traffic control sign and light replacement and repair 
3	Above Road Work - overpasses, overhead signs, overhead wires, etc. 
4	Below road work - boring, bridge repair, etc.
5	Barrier repair, guardrails, walls, etc. – Non-changing   
6	Non-drivable surface work or repair, shoulder or median repair, re-pavement, or creation  
7	Repainting restriping, not changing.  Expected that new paint will be within 1 meter of old paint.  No new items added.
8	Re-surfacing with repaint, not changing.  Expecting that new surface and paint will be within 1 meter of old surface and paint.
9	Location of Sign change or new signs (non-traffic control).  (This is frequently used as a localizer in HD maps)
10	Location, function, or indication of sign or light change for traffic control devices.  
11	Barrier creation or change – new guardrails, new retaining walls, new K-barriers. 
12	Repaint with change.  Adding new lanes, moving lanes, adding stop bars, etc.  
13	Resurface with change.  Adding new lanes, moving lanes, adding or changing connectivity (turn lanes)
14	Road move.  Physically moving the road (new bridge, removing a sharp curve, etc.
15	New road creation. 

0-8 would be considered non-architectural changing construction zones.  Meaning, any previous LiDAR scanning based map would still be valid after the work was complete. 

9-15 would be considered architecturally changing construction zones.  Meaning, any previous LiDAR scanning based map would require re-acquisition once construction is complete.

**Comment by CraigMoore-Sea** [comment]
Should this field be renamed Activity Type? Many jurisdictions like Seattle are using the same specification for all our road closures; parades, farmer's markets, etc.  Naming it Activity Type makes the spec more flexible moving forward.

**Comment by j-d-b** [comment]
> Naming it Activity Type makes the spec more flexible moving forward.

This also separates it from the WorkType data frame defined in the TMDD if we aren't going to conform to that.

**Comment by j-d-b** [comment]
I don't have any specifics to add/remove from the list from @davidcraig4300, but I do think each type needs a concise human-readable string. In this case, the enumerated type `workType` would be added to the common core data and would consist of the 16 defined types by their string type name.

Another approach is that @davidcraig4300's categorization list could be a classification and within each classification there is another enumerated type for each specific classification. In this case, the data frame `WorkType` would be added to the common core data. This data frame would contain `workCategory` and `detailedWorkType` (field names for example only; open to discussion/change). `workCategory` would contain the types defined by @davidcraig4300 and `detailedWorkType` would provide more detail on the selected `workCategory` type. For example, if `workCategory` is `Barrier creation or change`, `detailedWorkType` could be any one of `Bridge repair`, `New guardrails`, `New retaining walls`, `New K-barriers`, or anything else we decide would fit in this category.

The intention of the original PR for MassDOT's use case was for this field to be beneficial for humans. Many of the enumerations I defined in the PR would fall under a single one of @davidcraig4300's classifications and thus that specificity (though perhaps useless information for mapping/CVs) would be lost. `detailedWorkType` would include that information as well as including the information useful for mapping/machines.

**Comment by davidcraig4300** [comment]
@j-d-b 
I totally agree that this could be a nested field that provides more resolution.  I think that is a fantastic idea.  However, I see that as the next phase in this development.  Let's get the construct in place for this release, then add a layer in the next release.  The logic to that is, this level of information instantly becomes usable for map makers to determine when they have to re-scan the affected areas.  Adding the next layer is not required for them.  But, I do agree that the more information the better.  So, does it make sense to you to start with the primary layer of information that I laid out, then add to it on a subsequent release?

**Comment by j-d-b** [comment]
@davidcraig4300 the issue with starting as a data field and changing to a data frame is that this would be a breaking change. We can get around this in a couple ways.

## Options
### Option 1.
One option is to define the data frame with a single field in it, the `workCategory` you defined, then add the `workCategoryType` field in a later release. Thus the structure wouldn't change as we'd just be adding a new field in the future rather than changing a field to a data frame. For v2 this is extra nesting that is useless, but it allows us to avoid having to make a breaking change.

### Option 2.
Another option is to start with the `workCategory` data field (that you defined) in the common core data and then add the `workCategoryType` to the common core data as well in a later release, without nesting. This is a bit of clutter later on and we lose the clarity of combining closely related fields in the same data frame but the v2 release would be cleaner.

## Examples
JSON examples for options **1.** and **2.** below. Again all field names are open to discussion, please provide thoughts on these.

### Option 1.
#### v2 release
```json
{
  "WorkZoneActivity": {
    "WorkType": {
      "workCategory": "Barrier Creation or Change"
    }
  }
}
```

#### Later release
```json
{
  "WorkZoneActivity": {
    "WorkType": {
      "workCategory": "Barrier Creation or Change",
      "workCategoryType": "New Guardrails"
    }
  }
}
```

### Option 2.
#### v2 release
```json
{
  "WorkZoneActivity": {
    "workCategory": "Barrier Creation or Change"
  }
}
```

#### Later release
```json
{
  "WorkZoneActivity": {
    "workCategory": "Barrier Creation or Change",
    "workCategoryType": "New Guardrails"
  }
}
```

**Comment by davidcraig4300** [comment]
@j-d-b 

I see your point that the 2nd way is "cleaner" but I really like the idea of option 1 (which keeps these 2 fields connected maybe even indented).   So, how would this be annotated if multiple items are being changed.  i.e. add repainting of lines with the new guardrail addition?  I don't believe we want this to drive a unique WZDx report for each work category (item changing).  I believe this could be used to show multiple items changing simultaneously.  It looks to me like the 1st option would keep the change associated with the category connected with the category type.  Or am I missing something?   So, WZDx V2 would be released with the Work Category.  Then WZDx V3 (or later) can be released with the Work Category Type being added.  Correct?

**Comment by davidcraig4300** [comment]
Cleaning up the description based on all past conversations.

This required field will now be called Activity Type (no longer called Work Type).  It is not limited to just one identifier (multiple identifiers could exist in the same WZDx report).  

This should include the following categorization of construction zones (note there has been a couple subtle changes):

Identifier     Description
0              No change, this would be used for trash cleaning, mowing, general landscaping 
                maintenance, or other non road impacting access required.
1              Pothole repair, road crack repair and sealing, and other small road defect repairs
2              Non traffic control sign replacement, repair, installation
3              Traffic control sign and light replacement and repair
4              Above Road Work - overpasses, overhead signs, overhead wires, etc.
5              Below road work - boring, bridge repair, etc.
6              Barrier repair, guardrails, walls, etc. – Non-changing
7              Non-drivable surface work or repair, shoulder or median repair, re-pavement, or creation
8              Repainting restriping, not changing. Expected new paint will be within 1 meter of old 
                paint. No architectural change.
9              Re-surfacing with repaint, not changing. Expecting new surface and paint will be within 
                1 meter of old surface and paint.  No architectural change.
10            Traffic control device change or creation - location, function, or indication of sign or light.
11            Barrier creation or change – new guardrails, new retaining walls, new K-barriers.
12            Repaint with change. Adding new lanes, moving lanes, adding stop bars, etc.
13            Resurface with change. Adding new lanes, moving lanes, adding or changing connectivity 
                (turn lanes)
14            Road move. Physically moving the road (new bridge, removing a sharp curve, etc.
15            New road creation, new road connectivity.

0-9 would be considered non-architectural changing construction zones. Meaning, any previous LiDAR scanned based map would still be valid after the work was complete.

10-15 would be considered architecturally changing construction zones. Meaning, any previous LiDAR scanned based map would require re-acquisition once construction is complete.

@j-d-b can you please help me get the formatting correct to finalize this pull request?  Thanks!

**Comment by j-d-b** [comment]
I've discussed the most recent list of proposed types from @davidcraig4300 with the MassDOT team, summarized our comments, and put together an updated proposal below.

**Note:** Below I use the terms "previous proposed type". This refers to the most recent list from @davidcraig4300.

## Comments
It’s a commitment from all the DOTs to enter this level of detail for the work type and often multiple of these types occur in the same work zone. DOT's cannot be expected to update the `activityType` information when the phase of work changes. However, choosing multiple categorizations when creating the activity and leaving them unchanged as the work progresses is acceptable. We need to clarify this field is not expected to change frequently.

Additionally, the categorization of *overhead* vs *roadside* is important--more important the "traffic control" vs "non-traffic control". The proposed list of types specified 'Above Road Work', though 'Roadside' wasn't clarified. Previously proposed types 2 and 3 touch on this but are a bit mixed as signals may be overhead but were put in a different category. We've separated these out in the new proposed types below.

## Questions
1. What would you consider a "non-traffic control sign" (as described in type 2) and what was the reasoning for separating this from a "traffic control sign" in  previous proposed types 2 and 3? To MassDOT, all signs (guide, warning, regulatory, and information) are "traffic control signs" (with the exception of VMS).

## Updated Proposal
We've put together two options for the data structure and complete list of enumerated types below. Option 1 is more similar to @davidcraig4300's proposed types, and Option 2 is more concise and clear, though a bit less specific. Option 2 is our preference.

### Option 1
This approach involves adding a new field, `activityTypes`, to the work zone activity common core data. This field would be a list of 1 or more of the new **Enumerated Types** proposed in this section.

#### Proposed Types
Based on our comments above, we've slightly modified the list of previously proposed types as well as defining a concise 'Type Name' to describe each type.

\# | Type Name | Description | Category
--- | --- | --- | ---
0 | `Maintenance` | Work with no impact on the roadway. This includes events such as trash pickup, mowing, landscaping. | Non-architectural
1 | `Minor Road Defect Repair` | Pothole repair, road crack repair and sealing, and other small road defect repairs. | Non-architectural
2 | `Roadside Sign Repair or Replacement` | Replacement or repair of signs on the roadside (in the ground), not overhead. This includes guide, warning, regulatory, and information signs. Non-architectural counterpart to \#<i></i>10. | Non-architectural
3 | `General Roadside Work` | Work that is isolated to the side of the road and not in the main travel way, such as repair, replacement, or addition of streetlights and VMS. | Non-architectural
4 | `Overhead Traffic Control Device Repair or Replacement` | Repair or replacement of an overhead sign, signal, or similar. Non-architectural counterpart to \#<i></i>11. | Non-architectural
5 | `General Overhead Work` | Work on overpasses, overhead VMS, wires, etc. This type of work requires a bucket truck or similar setup rather than being isolated to the side of the road. | Non-architectural
6 | `General Below-Road Work` | Work occurring below the road such as boring or bridge repair. | Non-architectural
7 | `Barrier Repair or Replacement` | Repair or replacement of barriers, guardrails, retaining walls, K-barriers, or similar. Non-architectural change counterpart to \#<i></i>12. | Non-architectural
8 | `Non-Drivable Surface Work` | Creation or repair of non-drivable surfaces such as the shoulder or median. | Non-architectural
9 | `Repainting or Re-striping` | Repainting or re-striping is considered when new paint is expected to be within 1 meter of the old paint. Non-architectural change counterpart to \#<i></i>13.| Non-architectural
10 | `Roadside Sign Creation or Change` | Creation or change (e.g. in location or function) of a roadside sign. Architectural change counterpart to \#<i></i>2. | Architectural
11 | `Overhead Traffic Control Device Creation or Change` | Creation or change (e.g. in location or function) of an overhead sign, signal, or similar. Architectural change counterpart to \#<i></i>4. | Architectural
12 | `Barrier Creation or Change` | Creation or change of barriers, guardrails, retaining walls, K-barriers, or similar. Architectural change counterpart to \#<i></i>7. | Architectural
13 | `Painting` | Painting with a change, such as adding new lanes, moving lanes, adding stop bars/lines, etc. Architectural change counterpart to \#<i></i>9. | Architectural
14 | `Resurfacing` | New resurfacing, such as adding new lanes, moving lanes, or adding or changing connectivity (turn lanes). | Architectural
15 | `Roadway Relocation `| Physically relocating the road, such as adding a bridge or removing a sharp curve. | Architectural
16 | `Roadway Creation` | Adding a new road. | Architectural

#### JSON Example
```json
{
  "WorkZoneActivity": {
    "activityTypes": [
      "Barrier Creation or Change",
      "Minor Road Defect Repair"
    ]
  }
}
```

### Option 2
Rather than relying on documentation to indicate which enumerated types represent an architectural change, the new `activityTypes` field could include a list of new **Data Frames** which contain the enumerated type and another field (`isArchitecturalChange`) which explicitly shows whether or not this activity work type is associated with an architectural change.

This could allow us to cut down the list of enumerated types by combining all those that have a non-architectural/architectural counterpart (i.e. Option 1 proposed types \#<i></i>2 & \#<i></i>10, \#<i></i>4 & \#<i></i>11, \#<i></i>7 & \#<i></i>12, \#<i></i>9 & \#<i></i>13), as well as combining \#<i></i>2 & \#<i></i>3 and \#<i></i>4 & \#<i></i>5. Thus the enumerated types list will be much more concise.

For example, `Roadside Sign Repair or Replacement` (\#<i></i>2), `Roadside Sign Creation or Change` (\#<i></i>9), and `General Roadside Work` (\#<i></i>3) could be combined to become `Roadside Work`. The `isArchitecturalChange` field would show whether the specific `Roadside Sign Work` was accompanied by an architectural change. The ability to distinguish if the type of roadside work is sign work is of little importance to MassDOT and the architectural change aspect which inspired the initial separation and benefit to mapping agencies is still present in the `isArchitecturalChange` field.

This is MassDOT's/my preferred option as the enumerated type is the cleanest and the format is the most flexible as one type isn't tied to being an architectural or non-architectural change.

#### Proposed Types
The list of types for option 2 is more concise.

\# | Type Name | Description
--- | --- | ---
0 | `Maintenance` | Work with no impact on the roadway. This includes events such as trash pickup, mowing, landscaping.
1 | `Minor Road Defect Repair` | Pothole repair, road crack repair and sealing, and other small road defect repairs.
2 | `Roadside Work` | Work that is isolated to the side of the road and not in the main travel way, such as repair, replacement, or addition of streetlights, VMS, signs (guide, warning, regulatory, and information signs) in the ground. This type includes creation and change (in location or function) of signs and signals; in this case `isArchitecturalChange` will be `true`.
3 | `Overhead Work` | Work that occurs above the road, such as repair/replacement of overpasses, overhead VMS, wires, overhead signs, signals, etc. This type of work requires a bucket truck or similar setup rather than being isolated to the side of the road. This type includes creation or change (in location or function) of overhead signs and signals; in this case `isArchitecturalChange` will be `true`.
4 | `Below-Road Work` | Work occurring below the road such as boring or bridge repair.
5 | `Barrier Work` | Repair, replacement, addition, or change of barriers, guardrails, retaining walls, K-barriers, or similar. If creation or change, `isArchitecturalChange` will be `true`.
6 | `Surface Work` | New resurfacing, such as adding new lanes, moving lanes, or adding or changing connectivity (turn lanes), as well as creation or repair of non-drivable surfaces such as the shoulder or median. For new surfaces/resurfacing, `isArchitecturalChange` will be `true`.
7 | `Painting` | Repainting, re-striping, adding new lanes, moving lanes, adding stop bars/lines, etc. `isArchitecturalChange` will be `false` when new paint is expected to be within 1 meter of the old paint.
8 | `Roadway Relocation `| Physically relocating the road, such as adding a bridge or removing a sharp curve.
9 | `Roadway Creation` | Adding a new road.

#### JSON Example
```json
{
  "WorkZoneActivity": {
    "activityTypes": [
      {
        "typeName": "Barrier Work",
        "isArchitecturalChange": true
      },
      {
        "typeName": "Minor Road Defect Repair",
        "isArchitecturalChange": false
      }
    ]
  }
}
```

**Comment by sergebeaudry** [comment]
I like option 2 because less elements to select from making it easier for the end user.

**Comment by davidcraig4300** [comment]
I also really like option 2 the best.  It spells out the architecturally changing vs non architecturally changing work.  This actually even works better for our use case!    

To answer your question, non traffic control signs are information signs.  i.e. exit services, mile markers, distance to towns, etc. 

I am happy if you want to make option 2, the official pull request.

**Comment by j-d-b** [comment]
> I am happy if you want to make option 2, the official pull request.

I've updated the pull request per option 2.

**Comment by Mahsa-Ettefagh** [comment]
**This pull request is now open for voting. Please cast your vote for "OPTION 2" by leaving a “yes”, “no”, or “neutral” comment under the pull request. The voting will remain open until Wednesday, October 16th.**

**Comment by sergebeaudry** [comment]
Yes

**Comment by j-d-b** [comment]
Yes 👍

**Comment by davidcraig4300** [comment]
Yes

**Comment by sghorbanian** [comment]
yes

**Comment by CraigMoore-Sea** [comment]
Yes

**Comment by SinclairStolle-IowaDOT** [comment]
yes

**Comment by GreyIC** [comment]
Yes

**Comment by sknick-iastate** [comment]
yes

**Comment by DavidRush123** [comment]
Yes

**Comment by gaissert** [comment]
Yes

**Comment by Mahsa-Ettefagh** [comment]
On behalf of Alex Demisch - San Francisco Municipal Transportation Agency - Yes

**Comment by Mahsa-Ettefagh** [comment]
On behalf of Derald Dudley - U.S,DOT - Yes

**Comment by michelle315** [comment]
On behalf of Neil Boudreau, MassDOT - Yes

**Comment by kpwebb** [comment]
Yes

**Comment by j-d-b** [comment]
These changes need to be implemented in a new PR that branches off of #54 (or one if its child branches) so that they are congruent with the relational data model and can be automatically merged.

I can make these changes/a new PR, though I need to know how/when we will perform the PR merging process for v2 and which branch I should base the changes on.

**Comment by j-d-b** [comment]
The activity type approved here has been adapted to the relational model and replaced with PR #59.

**Pull request closed without merging**
