### PR TITLE
Require GeoJson Formatting

### PR DESCRIPTION
**Pull request by DeraldDudley**
**Require published feeds be formatted according to the GeoJSON specification.**

GeoJSON is a geospatial data interchange format based on JavaScript Object Notation (JSON). It defines several types of JSON objects and the manner in which they are combined to represent data about geographic features, their properties, and their spatial extents. GeoJSON uses a geographic coordinate reference system, World Geodetic System 1984 (i.e., WGS84), and units of decimal degrees. 

The GeoJSON format is the best fit for the specification for a number of reasons.
- The format is designed to exchange spatial data, which is a primary goal of the Work Zone Data Working Group.
- It is an open specification and does not carry licensing burdens.
- Because GeoJSON formatted-data is published as text files, there is a low technological burden of entry.
- GeoJSON validation, mapping, and visualization tools already exists and will ease adoption by producers and consumers.

This pull request, if accepted will address, Issues and Pull Requests #21, #23, #40, #41, #42.

### CODE REVIEW

**Comment by sbma44** [comment]
yes!

**Comment by sammyghorbanian** [comment]
yes - sammy on behalf of Uber ATG

**Comment by sergebeaudry** [comment]
Yes

**Comment by DrewClark-KY** [comment]
Yes - KYTC

**Comment by sknick-iastate** [comment]
@DeraldDudley This current pull request contains a lot of the relational data model, lane impacts, and activity that were part of PR #50.  Since it looks like PR #54 is going to be approved, should we build off of that branch with this PR instead?

I'd also like to see the sample and example files updated with geoJSON to get an idea of how the specification looks in geoJSON.  I think the specification in whole should also be reviewed and any references to geoJSON removed like in the [create feeds directory](https://github.com/usdot-jpo-ode/jpo-wzdx/tree/master/create-feed#data-file-types)

**Comment by DeraldDudley** [comment]
> @DeraldDudley This current pull request contains a lot of the relational data model, lane impacts, and activity that were part of PR #50. Since it looks like PR #54 is going to be approved, should we build off of that branch with this PR instead?
> 
> I'd also like to see the sample and example files updated with geoJSON to get an idea of how the specification looks in geoJSON. I think the specification in whole should also be reviewed and any references to geoJSON removed like in the [create feeds directory](https://github.com/usdot-jpo-ode/jpo-wzdx/tree/master/create-feed#data-file-types)

@sknick-iastate Skylar, that seems like the most efficient route.  Should I update this PR to point to #54 ?

**Comment by DeraldDudley** [comment]
Yes - USDOT

**Comment by sknick-iastate** [comment]
> > @DeraldDudley This current pull request contains a lot of the relational data model, lane impacts, and activity that were part of PR #50. Since it looks like PR #54 is going to be approved, should we build off of that branch with this PR instead?
> > I'd also like to see the sample and example files updated with geoJSON to get an idea of how the specification looks in geoJSON. I think the specification in whole should also be reviewed and any references to geoJSON removed like in the [create feeds directory](https://github.com/usdot-jpo-ode/jpo-wzdx/tree/master/create-feed#data-file-types)
> 
> @sknick-iastate Skylar, that seems like the most efficient route. Should I update this PR to point to #54 ?

@DeraldDudley I'm not sure what the best way to do that is.  I would recommend starting a new branch since that would be cleaner but we would lose a lot of the content from this pull request.  This current PR has some things above what PR #54 has including the lanes and restrictions.

**Comment by mikedavidson-paturnpike** [comment]
Yes

**Comment by Mahsa-Ettefagh** [comment]
On behalf of Samuel Krassenstein (City of Detroit) - yes

**Comment by cfelice** [comment]
Yes - Utah Department of Transportation (UDOT)

**Comment by CraigMoore-Sea** [comment]
Yes - Seattle DOT

**Comment by kpwebb** [comment]
Yes -- SharedStreets

**Comment by alexdemisch** [comment]
Yes - SFMTA

**Comment by davidcraig4300** [comment]
Yes

**Comment by schnuerle** [comment]
Yes

**Comment by j-d-b** [comment]
I wanted to note that this pull request has conflicts with PR #54 (and thus PR #58) and also does not update the examples in the `create-feed` or use #54's new `sample-files` organization.

Thus, this PR can't be merged directly. The changes approved here should be made by branching off of #58, which seems like it branches off of #54 (which branches off of the current master branch, representing v1.1). The sample files and examples should also be updated. This should probably take place in a new PR. 

Then, these changes could be cleanly and automatically merged.

**Comment by sknick-iastate** [comment]
> I wanted to note that this pull request has conflicts with PR #54 (and thus PR #58) and also does not update the examples in the `create-feed` or use #54's new `sample-files` organization.
> 
> Thus, this PR can't be merged directly. The changes approved here should be made by branching off of #58, which seems like it branches off of #54 (which branches off of the current master branch, representing v1.1). The sample files and examples should also be updated. This should probably take place in a new PR. These changes could then be cleanly and automatically merged.

I agree

**Comment by natedeshmukhtowery** [comment]
Jacob – you’re exactly right. We noticed this part-way through the voting on #53 (which was developed off of PR50) and decided to let that voting continue and put together a new PR based on 54/58 for the purpose of merging into a final v2.

Since the purpose of PR53 is primarily to get approval on a transition to GeoJSON over the XML and JSON options in v1.1 – and the geometry elements were already included in the approved #54 – that seemed to be a straightforward path.

We’d love your help in doing that after WZDWG voting is complete.

**Comment by DeraldDudley** [comment]
My being a GitHub novice seems to have caused some consternation.  Sorry about that.  Happy to help sort through the mess to set things straight.  Also, happy to update the create-feed and sample-files content.

Derald Dudley
NGDA Transportation<https://communities.geoplatform.gov/ngda-transportation/> Theme Lead
FGDC Transportation Subcommittee<https://communities.geoplatform.gov/ngda-transportation/transportation-subcommittee/> Chair
Phone: 202.309.0940
Pronouns: he/him/his

The Office of Spatial Analysis and Visualization<http://maps.bts.dot.gov/>
Bureau of Transportation Statistics<http://www.rita.dot.gov/bts/>
Office of the Assistant Secretary of Transportation for Research and Technology<http://www.rita.dot.gov/>
United States Department of Transportation<http://www.transportation.gov/>

**Pull request merged**
