### PR TITLE
Adapting #33 to the relational data model: adding types_of_work table and type_name enumeration

### PR DESCRIPTION
**Pull request by j-d-b**
This PR adds a new optional `types_of_work` table and a `type_name` enumeration. These are based on PR #33.

## Types of Work Table
**Optional**

This table indicates the type(s) of work being done in a road event, if applicable (e.g. typical work zones), as well as noting if each type of work will result in an architectural change to the roadway.

This table is related to the [road_events](/data-tables/road_events.md) table by the foreign key road_event_id.  For every record in the road_event table there exists zero or more records in the types_of_work table.

Data Name|Data Type|Description|Conformance|Notes
-|-|-|-|-|
type_of_work_id|ID|Identifies the types_of_work record|Required|Primary key
[road_event_id](/data-tables/road_events.md)|ID|Identifies the road event to the type_of_work is related.|Required|Foreign key
type_name | Enumeration; Text|A high-level text description of the type of work being done.|Required|
is_architectural_change|Boolean|A flag indicating whether the type of work will result in an architectural change to the roadway.|Optional|

## Type Name Enumeration
Type Name | Description
--- | ---
**maintenance** | Work with no impact on the roadway. This includes events such as trash pickup, mowing, landscaping.
**minor-road-defect-repair** | Pothole repair, road crack repair and sealing, and other small road defect repairs.
**roadside-work** | Work that is isolated to the side of the road and not in the main travel way, such as repair, replacement, or addition of streetlights, VMS, signs (guide, warning, regulatory, and information signs) in the ground.
**overhead-work** | Work that occurs above the road, such as repair/replacement of overpasses, overhead VMS, wires, overhead signs, signals, etc. This type of work requires a bucket truck or similar setup rather than being isolated to the side of the road.
**below-road-work** | Work occurring below the road such as boring or bridge repair.
**barrier-work** | Repair, replacement, addition, or change of barriers, guardrails, retaining walls, K-barriers, or similar.
**surface-work** | New resurfacing, such as adding new lanes, moving lanes, or adding or changing connectivity (turn lanes), as well as creation or repair of non-drivable surfaces such as the shoulder or median.
**painting** | 	Repainting, re-striping, adding new lanes, moving lanes, adding stop bars/lines, etc. ***Note:** `is_architectural_change` field should be false when new paint is expected to be within 1 meter of the old paint.*
**roadway-relocation** | Physically relocating the road, such as adding a bridge or removing a sharp curve.
**roadway-creation** | Adding a new road.

## Todo
- [x] Update ERD

### CODE REVIEW

**Comment by j-d-b** [comment]
@DeraldDudley let me know if you can generate the updated ERD to complete the remaining todo items.

**Comment by DeraldDudley** [comment]
Working on it this morning…

Derald Dudley
Theme Lead  - Transportation NGDA<https://communities.geoplatform.gov/ngda-transportation/>
Chair - FGDC Transportation Subcommittee<https://communities.geoplatform.gov/ngda-transportation/transportation-subcommittee/>
Geographer - The Office of Spatial Analysis and Visualization<http://maps.bts.dot.gov/>
Phone: 202.309.0940
Pronouns: he/him/his

Bureau of Transportation Statistics<http://www.rita.dot.gov/bts/>
Office of the Assistant Secretary of Transportation for Research and Technology<http://www.rita.dot.gov/>
United States Department of Transportation<http://www.transportation.gov/>

**Comment by j-d-b** [comment]
> Working on it this morning…

No need, @sknick-iastate already completed this task.

**Comment by DeraldDudley** [comment]
Right on.  Thank you.

Derald Dudley
Theme Lead  - Transportation NGDA<https://communities.geoplatform.gov/ngda-transportation/>
Chair - FGDC Transportation Subcommittee<https://communities.geoplatform.gov/ngda-transportation/transportation-subcommittee/>
Geographer - The Office of Spatial Analysis and Visualization<http://maps.bts.dot.gov/>
Phone: 202.309.0940
Pronouns: he/him/his

Bureau of Transportation Statistics<http://www.rita.dot.gov/bts/>
Office of the Assistant Secretary of Transportation for Research and Technology<http://www.rita.dot.gov/>
United States Department of Transportation<http://www.transportation.gov/>

**Pull request merged**
